global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alerts/*.rules.yml"


scrape_configs:
  - job_name: 'prometheus' 
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jupyterhub'
    static_configs:
      - targets: ['jupyterhub:8083']  

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'python_exporter'
    static_configs:
      - targets: ['jupyterhub-metrics-exporter:8085']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


