FROM jupyterhub/jupyterhub:5

RUN pip install --no-cache \ 
    oauthenticator \
    dockerspawner \ 
    jupyterhub-nativeauthenticator \
    prometheus-client

#COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
